# Generated by Django 4.2.1 on 2023-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_bearch',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='icon',
            field=models.ImageField(default='/media/default.png', upload_to='icon/'),
        ),
    ]
